version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch-agro
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - agro-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana-agro
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - agro-net

  api:
    image: agrosolutions-history-api
    container_name: agro-history-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://admin:senha@host.docker.internal:27017
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - agro-net

volumes:
  elastic_data:
    driver: local

networks:
  agro-net:
    driver: bridge