apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: history-context
spec:
  type: LoadBalancer 
  selector:
    app: history-api
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8080 