<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AgroSolutions.History.Domain\AgroSolutions.History.Domain.csproj" />
    <ProjectReference Include="..\AgroSolutions.History.Application\AgroSolutions.History.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Persistence\Context\" />
    <Folder Include="Persistence\Mappings\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
